### ISSUE TITLE
Wrong XML sequence for degrees

### ISSUE THREAD

**Issue by infojunkie** [no-chris/chord-symbol-musicxml#2]
The MusicXML [`degree` element specifies a _sequence_ of sub-elements](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-degree.htm) - creating such sub-elements out of sequence fails XML validation, as per [my latest build](https://github.com/infojunkie/ireal-musicxml/runs/1730657218#step:6:121).

Here's [my own function to ensure that MusicXML sequences are correctly ordered](https://github.com/infojunkie/ireal-musicxml/blob/bea58352636856c59edacc18cf2165fd24c62c06/src/musicxml.js#L534-L553).

I also suggest to add tests here that validate the generated MusicXML ([example code here](https://github.com/infojunkie/ireal-musicxml/blob/main/test/musicxml.spec.js#L47-L48)).

**Comment by no-chris** [comment]
Right, `degree-alter` is always there, I totally missed that 🤪 

> I also suggest to add tests here that validate the generated MusicXML (example code here).

👍🏻

**Comment by no-chris** [comment]
Both issues should be fixed in `v0.1.1` branch would you mind testing it before I release? 🙏🏻

**Comment by infojunkie** [comment]
Build passing with `v0.1.1` :+1:

**Comment by infojunkie** [comment]
Works great on my [latest build](https://github.com/infojunkie/ireal-musicxml/commit/250506a27da0eec95df2ea7d428b50c5c520f220) :pray:
