### ISSUE TITLE
alt chord should return "add" or "alter" degrees?

### ISSUE THREAD

**Issue by infojunkie** [no-chris/chord-symbol-musicxml#6]
Here's the output for chord "D7alt":
```
      <harmony>
        <root>
          <root-step>D</root-step>
        </root>
        <kind text="7alt">dominant</kind>
        <degree print-object="no">
          <degree-value>5</degree-value>
          <degree-alter>-1</degree-alter>
          <degree-type>alter</degree-type>
        </degree>
        <degree print-object="no">
          <degree-value>5</degree-value>
          <degree-alter>1</degree-alter>
          <degree-type>alter</degree-type>
        </degree>
        <degree print-object="no">
          <degree-value>9</degree-value>
          <degree-alter>-1</degree-alter>
          <degree-type>alter</degree-type>
        </degree>
        <degree print-object="no">
          <degree-value>9</degree-value>
          <degree-alter>1</degree-alter>
          <degree-type>alter</degree-type>
        </degree>
        <degree print-object="no">
          <degree-value>11</degree-value>
          <degree-alter>1</degree-alter>
          <degree-type>alter</degree-type>
        </degree>
        <degree print-object="no">
          <degree-value>13</degree-value>
          <degree-alter>-1</degree-alter>
          <degree-type>alter</degree-type>
        </degree>
      </harmony>
```
I am wondering which degrees should be "alter", and which should be "add". My understanding of [`degree-type`](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-degree-type.htm) is that any degree that exists in the core `kind` should be "alter"ed, and other ones would be "add"ed. 

For reference, here's [how my own code computes this](https://github.com/infojunkie/ireal-musicxml/blob/bea58352636856c59edacc18cf2165fd24c62c06/src/musicxml.js#L980-L999), before merging with `chord-symbol@v2.x` + `chord-symbol-musicxml`. The idea is to "add" all degrees except the first 5th, since the core `kind` is guaranteed (per my function's logic) to not contain the other degrees.

**Comment by no-chris** [comment]
good question, but above my paygrade 😅 

https://github.com/w3c/musicxml/issues/369
